# -*- coding: utf-8 -*-
"""Numpy_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQdI-_xFQmUv0Wke9mp_It-5THqicFCP

Numpy - Numerical python

1.Allows several mathetical operations
2.faster operations
"""

import numpy as np

"""List vs Numpy timing"""

from time import process_time

"""Time taken by list"""

python_list = [i for i in range(10000) ]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time() 

print(end_time - start_time)

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array+= 5  #np_array = np_array + 5

end_time = process_time() 

print(end_time - start_time)

"""Numpy arrays"""

#List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

#creating one dimensional array
a = np.array([1,2,3,4,5])
print(a)

a.shape

#create two dimensional array
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

b.shape

c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

#create a numpy array of zeros
x=np.zeros((4,5))
print(x)

#create a numpy array of ones
y=np.ones((3,3))
print(y)

#array of a particular values 
z=np.full((5,4),5)
print(z)

#create an identity matrix
a = np.eye(5)
print(a)

#create a numpy array with random values
b = np.random.random((3,4))
print(b)

# random integer values array with in a specific range
c = np.random.randint(10,100,(3,5))
print(c)

#array of evenly spaced values --> specifying the number of values required
d=np.linspace(10,30,6)
print(d)

# array of evenly spaced values--> specifying the step
e =np.arange(10,30,5) #step value like 5 10 15 20
print(e)

#convert an list to an array
list2 = [10,20,30,40,50,60]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

#Analysing a numpy array
c = np.random.randint(10,90,(5,5))
print(c)

#array dimension
print(c.shape)

#number of dimensions
print(c.ndim)

#number of elements in an array
print(c.size)

#checking the data type of the values in the array
print(c.dtype)

#mathematical operation on a np array
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2)      # + concatenate or joins two list

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

#array manipulatio
array = np.random.randint(0,10,(2,3)) #2 cross 3 matrix
print(array)
print(array.shape)

# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

trans2 = array.T
print(trans2)
print(trans2.shape)

# Reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

b = a.reshape(3,2)
print(b)
print(b.shape)

